# Generated by Django 6.0.5 on 2026-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('content_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=2048)),
                ('source_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('source_label', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('inbox', 'inbox'), ('corpus', 'corpus'), ('void', 'void')], default='inbox', max_length=32)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('file_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['downloaded_at'],
            },
        ),
    ]
