# Generated by Django 6.0.5 on 2026-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('4chan', '4chan'), ('imgur', 'Imgur'), ('tumblr', 'Tumblr'), ('pixelfed', 'Pixelfed')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type', 'name'],
                'unique_together': {('type', 'name')},
            },
        ),
    ]
