# Generated by Django 6.0.5 on 2026-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
