# Generated by Django 6.0.5 on 2026-05-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_image_is_nsfw_source_is_nsfw'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
