# Generated by Django 6.0.5 on 2026-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='phash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
    ]
