# Generated by Django 6.0.5 on 2026-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_image_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_hours', models.PositiveSmallIntegerField(default=6)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
