# Generated by Django 6.0.5 on 2026-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_scrape_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='void_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
