# Generated by Django 6.0.5 on 2026-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_void_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_purged',
            field=models.BooleanField(default=False),
        ),
    ]
