# Generated by Django 6.0.5 on 2026-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_tag_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='cursor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('4chan', '4chan'), ('imgur', 'Imgur'), ('tumblr', 'Tumblr'), ('pixelfed', 'Pixelfed'), ('mastodon', 'Mastodon')], max_length=20),
        ),
    ]
