# Generated by Django 6.0.5 on 2026-05-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_source_cursor_alter_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mattermost_enabled', models.BooleanField(default=False)),
                ('mattermost_base_url', models.CharField(blank=True, max_length=255)),
                ('mattermost_token', models.CharField(blank=True, max_length=255)),
                ('mattermost_channel_id', models.CharField(blank=True, max_length=64)),
                ('mattermost_message_prefix', models.CharField(blank=True, max_length=255)),
                ('signal_enabled', models.BooleanField(default=False)),
                ('signal_api_url', models.CharField(blank=True, max_length=255)),
                ('signal_sender', models.CharField(blank=True, max_length=32)),
                ('signal_recipients', models.TextField(blank=True)),
                ('signal_message_prefix', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'notification config',
            },
        ),
    ]
