# Generated by Django 6.0.5 on 2026-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_notificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='keyword_suggestions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
