# Generated by Django 6.0.5 on 2026-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0017_remove_image_keyword_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfw_threshold', models.PositiveSmallIntegerField(default=1)),
                ('nsfw_threshold', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='predicted_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
