# Generated by Django 6.0.5 on 2026-05-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0018_reviewthresholds_image_predicted_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('service', models.CharField(choices=[('mattermost', 'Mattermost'), ('signal', 'Signal')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('mm_base_url', models.CharField(blank=True, max_length=255)),
                ('mm_token', models.CharField(blank=True, max_length=255)),
                ('mm_channel_id', models.CharField(blank=True, max_length=64)),
                ('mm_message_prefix', models.CharField(blank=True, max_length=255)),
                ('signal_api_url', models.CharField(blank=True, max_length=255)),
                ('signal_sender', models.CharField(blank=True, max_length=32)),
                ('signal_recipients', models.TextField(blank=True)),
                ('signal_message_prefix', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'notification channel',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='NotificationConfig',
        ),
    ]
