# Generated by Django 6.1.1 on 2026-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0021_image_embedding_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewthresholds',
            name='queue_order',
            field=models.CharField(choices=[('oldest', 'Oldest first'), ('newest', 'Newest first'), ('shuffle', 'Shuffled')], default='oldest', max_length=10),
        ),
    ]
