# Generated by Django 6.1.1 on 2026-10-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0022_reviewthresholds_queue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='search_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='search_embedding_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
