# Generated by Django 6.1.1 on 2026-10-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0023_image_search_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewthresholds',
            name='queue_order',
            field=models.CharField(choices=[('oldest', 'Oldest first'), ('newest', 'Newest first'), ('shuffle', 'Shuffled'), ('uncertain', 'Uncertain first')], default='oldest', max_length=10),
        ),
    ]
