# Generated by Django 6.1.1 on 2026-10-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0024_review_order_uncertain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_path',
            field=models.CharField(db_index=True, max_length=2048),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_purged', 'score', 'is_nsfw', 'queue_seen_at', 'downloaded_at', 'content_hash', 'predicted_score'], name='image_review_queue_idx'),
        ),
    ]
