# Generated by Django 6.1.1 on 2026-10-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0025_image_review_queue_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(condition=models.Q(('embedding__isnull', False)), fields=['embedding_model', 'is_purged'], name='image_taste_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(condition=models.Q(('search_embedding__isnull', False)), fields=['search_embedding_model', 'is_purged'], name='image_search_vector_idx'),
        ),
    ]
