# Generated by Django 6.1.1 on 2026-10-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0026_image_vector_count_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_purged', 'score', 'is_nsfw', 'queue_seen_at', 'content_hash', 'predicted_score'], name='image_review_shuffle_idx'),
        ),
    ]
