# Generated by Django 6.1.1 on 2026-10-03 19:13

from django.db import migrations, models
from django.db.models import Q


def mark_existing_decisions(apps, schema_editor):
    """
    Every rated image and every image flagged so far counts as decided (NSFW
    contract N7): until this field existed the operator set every flag by
    hand and looked at every image they rated, so today's training set stays
    exactly as it was. From here on only a rating or a hand toggle adds a
    decision; the model's flags stay undecided.
    """
    Image = apps.get_model("ratings", "Image")
    Image.objects.filter(Q(score__isnull=False) | Q(is_nsfw=True)).update(nsfw_judged=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0027_image_review_shuffle_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nsfw_judged',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_decisions, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['nsfw_judged', 'is_nsfw', 'is_purged'], name='image_nsfw_judged_idx'),
        ),
    ]
