# Generated by Django 6.1.1 on 2026-10-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0028_image_nsfw_judged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('4chan', '4chan'), ('imgur', 'Imgur'), ('tumblr', 'Tumblr'), ('pixelfed', 'Pixelfed'), ('mastodon', 'Mastodon'), ('flickr', 'Flickr')], max_length=20),
        ),
    ]
