from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("stats/", views.stats, name="stats"),
    path("rate/inbox/", views.rate_inbox, name="rate_inbox"),
    path("rate/corpus/", views.rate_corpus, name="rate_corpus"),
    path("rate/void/", views.rate_void, name="rate_void"),
    path("rate/nsfw/", views.rate_nsfw_inbox, name="rate_nsfw_inbox"),
    path("rate/nsfw/inbox/", views.rate_nsfw_inbox, name="rate_nsfw_inbox"),
    path("rate/nsfw/corpus/", views.rate_nsfw_corpus, name="rate_nsfw_corpus"),
    path("rate/nsfw/corpus/<str:content_hash>/", views.rate_nsfw_corpus, name="review_nsfw_corpus_image"),
    path("rate/nsfw/corpus/<str:content_hash>/score/", views.score_nsfw_corpus, name="score_nsfw_corpus"),
    path("rate/nsfw/corpus/<str:content_hash>/trash/", views.trash_nsfw_corpus, name="trash_nsfw_corpus"),
    path("rate/nsfw/corpus/<str:content_hash>/purge/", views.purge_nsfw_corpus, name="purge_nsfw_corpus"),
    path("rate/nsfw/corpus/<str:content_hash>/fav/", views.toggle_fav_nsfw_corpus, name="toggle_fav_nsfw_corpus"),
    path("rate/nsfw/void/", views.rate_nsfw_void, name="rate_nsfw_void"),
    path("rate/fav/", views.rate_fav, name="rate_fav"),
    path("rate/nsfw/fav/", views.rate_nsfw_fav, name="rate_nsfw_fav"),
    path(
        "rate/<str:content_hash>/<str:action>/",
        views.submit_rating,
        name="submit_rating",
    ),
    path("nsfw-toggle/", views.nsfw_toggle, name="nsfw_toggle"),
    path("gallery/", views.gallery, name="gallery"),
    path("gallery/<str:content_hash>/action/", views.gallery_action, name="gallery_action"),
    path("tags/autocomplete/", views.tag_autocomplete, name="tag_autocomplete"),
    path("tags/<str:content_hash>/", views.update_image_tags, name="update_image_tags"),
    # Void grid — must be before the corpus wildcard routes.
    path("review/void/", views.review_void, name="review_void"),
    path("review/void/bulk/", views.void_bulk_rescue, name="void_bulk_rescue"),
    path("review/void/<str:content_hash>/", views.review_void, name="review_void_image"),
    path("review/void/<str:content_hash>/action/", views.void_review_action, name="void_review_action"),
    path("review/void/<str:content_hash>/grid-action/", views.void_grid_action, name="void_grid_action"),
    # Corpus review
    path("review/", views.review_corpus, name="review_corpus"),
    path("review/<str:content_hash>/", views.review_corpus, name="review_corpus_image"),
    path("review/<str:content_hash>/score/", views.score_corpus, name="score_corpus"),
    path("review/<str:content_hash>/trash/", views.trash_corpus, name="trash_corpus"),
    path("review/<str:content_hash>/purge/", views.purge_corpus, name="purge_corpus"),
    path("review/<str:content_hash>/fav/", views.toggle_fav_corpus, name="toggle_fav_corpus"),
    path("toggle/<str:content_hash>/nsfw/", views.toggle_nsfw, name="toggle_nsfw"),
    path("config/", views.config_view, name="config"),
    path("config/schedule/", views.set_scrape_schedule, name="set_scrape_schedule"),
    path("config/add/", views.source_add, name="source_add"),
    path("config/import/", views.source_import, name="source_import"),
    path("config/<int:pk>/toggle/", views.source_toggle, name="source_toggle"),
    path("config/<int:pk>/delete/", views.source_delete, name="source_delete"),
    path("scrape/", views.trigger_scrape, name="trigger_scrape"),
    path("train/", views.trigger_train, name="trigger_train"),
    path("train/<str:task_id>/status/", views.train_status, name="train_status"),
    path("logs/", views.logs_page, name="logs"),
    path("logs/entries/", views.log_entries, name="log_entries"),
    path("logs/clear/", views.log_clear, name="log_clear"),
]
